In [1]:
import numpy as np
import pandas as pd
import statistics

In [2]:
#loading data set
data = pd.read_csv(r"C:\Users\supri\Downloads\Indian_Cricket_Team_Dataset.csv")

In [3]:
data

Player Name  Age  Matches Played  Batting Average  Strike Rate
0       Player_1   26             456            27.70       188.21
1       Player_2   23             154            24.61       139.34
2       Player_3   32             210            36.87       182.79
3       Player_4   34             426            51.81       178.77
4       Player_5   30             221            49.80       162.44
..           ...  ...             ...              ...          ...
995   Player_996   24             279            23.46       187.80
996   Player_997   28             344            29.47       160.55
997   Player_998   23             126            49.30       124.71
998   Player_999   35              16            41.93       135.59
999  Player_1000   30             146            25.12       108.39

[1000 rows x 5 columns]

In [4]:
data['Age']

0      26
1      23
2      32
3      34
4      30
       ..
995    24
996    28
997    23
998    35
999    30
Name: Age, Length: 1000, dtype: int64

In [7]:
#Convert 'Age' column to a NumPy array.
age = np.array(data['Age'])
age

array([26, 23, 32, 34, 30, 27, 32, 24, 26, 29, 22, 26, 30, 30, 27, 24, 23,
       27, 27, 22, 25, 24, 21, 27, 31, 33, 25, 21, 35, 31, 24, 20, 31, 29,
       25, 32, 31, 28, 20, 30, 30, 34, 29, 35, 31, 31, 35, 34, 33, 33, 34,
       33, 22, 31, 26, 23, 35, 28, 22, 24, 22, 26, 24, 28, 26, 21, 23, 28,
       31, 33, 21, 29, 28, 29, 24, 21, 23, 31, 34, 31, 26, 31, 32, 27, 34,
       22, 33, 20, 23, 21, 27, 23, 21, 33, 25, 25, 29, 23, 25, 32, 34, 21,
       29, 31, 21, 29, 33, 23, 33, 34, 35, 34, 27, 33, 26, 31, 28, 33, 27,
       24, 35, 32, 21, 34, 24, 27, 29, 28, 31, 31, 31, 32, 28, 32, 34, 32,
       20, 28, 26, 28, 27, 20, 31, 27, 27, 34, 30, 22, 20, 27, 22, 22, 20,
       30, 24, 29, 26, 29, 28, 31, 26, 28, 27, 31, 21, 20, 35, 26, 26, 33,
       27, 24, 22, 31, 27, 25, 30, 22, 20, 22, 24, 34, 33, 22, 20, 24, 29,
       26, 34, 33, 26, 30, 28, 34, 34, 29, 29, 31, 32, 22, 34, 35, 26, 20,
       23, 32, 35, 23, 33, 24, 26, 26, 32, 34, 30, 32, 23, 32, 35, 26, 30,
       22, 25, 31, 21, 29

In [8]:
# Find the average age of players. 
age.mean()

27.57

In [9]:
# Find the oldest and youngest player age.
age.min()

20

In [10]:
age.max()

35

In [11]:
# Count the total number of players above 30 years old.
age[age > 30]

array([32, 34, 32, 31, 33, 35, 31, 31, 32, 31, 34, 35, 31, 31, 35, 34, 33,
       33, 34, 33, 31, 35, 31, 33, 31, 34, 31, 31, 32, 34, 33, 33, 32, 34,
       31, 33, 33, 34, 35, 34, 33, 31, 33, 35, 32, 34, 31, 31, 31, 32, 32,
       34, 32, 31, 34, 31, 31, 35, 33, 31, 34, 33, 34, 33, 34, 34, 31, 32,
       34, 35, 32, 35, 33, 32, 34, 32, 32, 35, 31, 32, 33, 31, 31, 31, 31,
       33, 33, 35, 31, 33, 33, 32, 33, 31, 34, 35, 35, 33, 31, 33, 31, 35,
       33, 31, 35, 35, 34, 34, 35, 35, 31, 35, 32, 31, 34, 35, 35, 31, 34,
       33, 31, 35, 35, 31, 35, 33, 31, 35, 35, 35, 33, 35, 33, 32, 35, 33,
       35, 32, 33, 35, 35, 35, 35, 31, 33, 33, 32, 33, 31, 34, 35, 31, 32,
       35, 35, 35, 31, 31, 33, 32, 33, 31, 32, 33, 34, 31, 34, 32, 35, 35,
       35, 34, 33, 35, 34, 34, 35, 32, 32, 31, 32, 35, 33, 35, 33, 31, 34,
       31, 35, 34, 34, 33, 32, 34, 31, 31, 31, 31, 32, 35, 33, 34, 35, 32,
       31, 33, 34, 31, 33, 34, 31, 34, 35, 33, 35, 32, 35, 32, 35, 34, 32,
       31, 35, 32, 33, 31

In [12]:
# Find the median batting average. 
data.head()

Player Name  Age  Matches Played  Batting Average  Strike Rate
0    Player_1   26             456            27.70       188.21
1    Player_2   23             154            24.61       139.34
2    Player_3   32             210            36.87       182.79
3    Player_4   34             426            51.81       178.77
4    Player_5   30             221            49.80       162.44

In [13]:
data['Batting Average'].median()

40.135

In [14]:
# Find the standard deviation of strike rates
data['Strike Rate'].std

<bound method Series.std of 0      188.21
1      139.34
2      182.79
3      178.77
4      162.44
        ...  
995    187.80
996    160.55
997    124.71
998    135.59
999    108.39
Name: Strike Rate, Length: 1000, dtype: float64>

In [15]:
# Find the 90th percentile of batting average
data.describe()

Age  Matches Played  Batting Average  Strike Rate
count  1000.000000      1000.00000       1000.00000  1000.000000
mean     27.570000       250.32600         39.76529   150.661230
std       4.666785       142.09216         11.47482    29.122759
min      20.000000        10.00000         20.01000   100.020000
25%      23.000000       126.00000         29.47750   125.355000
50%      28.000000       252.50000         40.13500   151.890000
75%      32.000000       370.25000         49.73250   176.095000
max      35.000000       500.00000         59.85000   199.970000

In [16]:
percentile_90 = np.percentile(data['Batting Average'], 90)
print(percentile_90)

55.323


In [17]:
# Find the number of players with strike rate above 150
strike_rate = data['Strike Rate'] > 150
strike_rate.sum()

513

In [18]:
# Reshape the first 20 batting averages into a 4x5 matrix.
bat_avg = data['Batting Average'].head(20)

In [19]:
bat_avg

0     27.70
1     24.61
2     36.87
3     51.81
4     49.80
5     22.20
6     38.21
7     40.90
8     45.78
9     46.01
10    34.59
11    42.43
12    39.24
13    55.40
14    41.21
15    37.64
16    36.18
17    42.90
18    52.16
19    41.54
Name: Batting Average, dtype: float64

In [20]:
bat_avg.shape

(20,)

In [21]:
matrix = bat_avg.to_numpy().reshape(4, 5)
print(matrix)

[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


In [22]:
# Compute row-wise sum of reshaped matrix
matrix.sum(axis=0)

array([122.13, 141.43, 159.91, 205.15, 178.56])

In [23]:
# Compute column-wise mean of reshaped matrix. 
matrix.mean(axis=1)

array([38.158, 38.62 , 42.574, 42.084])

In [24]:
# Transpose the reshaped matrix.
trans_mat = matrix.T
trans_mat

array([[27.7 , 22.2 , 34.59, 37.64],
       [24.61, 38.21, 42.43, 36.18],
       [36.87, 40.9 , 39.24, 42.9 ],
       [51.81, 45.78, 55.4 , 52.16],
       [49.8 , 46.01, 41.21, 41.54]])

In [25]:
# Find the variance of batting average. 
data['Batting Average'].var()

131.6715008167167

In [26]:
# Stack age and matches played horizontally.
stacked = np.stack((data['Age'],data['Matches Played']))
stacked

array([[ 26,  23,  32, ...,  23,  35,  30],
       [456, 154, 210, ..., 126,  16, 146]], dtype=int64)

In [29]:
# Split the batting average array into 5 equal parts.
split_arr = np.split(data['Batting Average'],5)

In [30]:
print(split_arr)

[0      27.70
1      24.61
2      36.87
3      51.81
4      49.80
       ...  
195    50.91
196    29.20
197    25.25
198    54.72
199    58.53
Name: Batting Average, Length: 200, dtype: float64, 200    21.25
201    49.25
202    56.38
203    54.29
204    58.58
       ...  
395    45.60
396    28.99
397    27.20
398    23.54
399    24.13
Name: Batting Average, Length: 200, dtype: float64, 400    43.39
401    47.53
402    35.90
403    39.20
404    47.44
       ...  
595    35.14
596    34.52
597    59.82
598    37.85
599    33.34
Name: Batting Average, Length: 200, dtype: float64, 600    43.22
601    23.55
602    58.47
603    45.40
604    50.19
       ...  
795    51.30
796    29.11
797    59.04
798    46.69
799    20.42
Name: Batting Average, Length: 200, dtype: float64, 800    30.22
801    30.43
802    22.77
803    58.39
804    39.13
       ...  
995    23.46
996    29.47
997    49.30
998    41.93
999    25.12
Name: Batting Average, Length: 200, dtype: float64]


In [31]:
s_a = np.split(bat_avg,5)
print(s_a)

[0    27.70
1    24.61
2    36.87
3    51.81
Name: Batting Average, dtype: float64, 4    49.80
5    22.20
6    38.21
7    40.90
Name: Batting Average, dtype: float64, 8     45.78
9     46.01
10    34.59
11    42.43
Name: Batting Average, dtype: float64, 12    39.24
13    55.40
14    41.21
15    37.64
Name: Batting Average, dtype: float64, 16    36.18
17    42.90
18    52.16
19    41.54
Name: Batting Average, dtype: float64]
